### ISSUE TITLE
[Bug] Test failure on 32-bit arches

### ISSUE THREAD

**Issue by werdahias** [Cykooz/libheif-sys#5]
I recently upload libheif-sys to debian experimental and noticed that most of the tests fail on 32-bit arches (arm(el,hf), i386, mipsel, powerpc, x32). 

Log:

```
running 9 tests
test bindings::bindgen_test_layout_heif_color_profile_nclx ... ok
test bindings::bindgen_test_layout_heif_decoding_options ... FAILED
test bindings::bindgen_test_layout_heif_init_params ... ok
test bindings::bindgen_test_layout_heif_encoding_options ... FAILED
test bindings::bindgen_test_layout_heif_error ... FAILED
test bindings::bindgen_test_layout_heif_depth_representation_info ... FAILED
test bindings::bindgen_test_layout_heif_plugin_info ... FAILED
test bindings::bindgen_test_layout_heif_writer ... FAILED
test bindings::bindgen_test_layout_heif_reader ... FAILED

failures:

---- bindings::bindgen_test_layout_heif_decoding_options stdout ----
thread 'bindings::bindgen_test_layout_heif_decoding_options' panicked at 'assertion failed: `(left == right)`
  left: `24`,
 right: `48`: Size of: heif_decoding_options', src/bindings.rs:1231:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_decoding_options
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:1231:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_decoding_options::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:1227:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- bindings::bindgen_test_layout_heif_encoding_options stdout ----
thread 'bindings::bindgen_test_layout_heif_encoding_options' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `24`: Size of: heif_encoding_options', src/bindings.rs:1751:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_encoding_options
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:1751:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_encoding_options::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:1747:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- bindings::bindgen_test_layout_heif_error stdout ----
thread 'bindings::bindgen_test_layout_heif_error' panicked at 'assertion failed: `(left == right)`
  left: `12`,
 right: `16`: Size of: heif_error', src/bindings.rs:122:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_error
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:122:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_error::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:119:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- bindings::bindgen_test_layout_heif_depth_representation_info stdout ----
thread 'bindings::bindgen_test_layout_heif_depth_representation_info' panicked at 'assertion failed: `(left == right)`
  left: `56`,
 right: `64`: Size of: heif_depth_representation_info', src/bindings.rs:610:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_depth_representation_info
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:610:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_depth_representation_info::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:606:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- bindings::bindgen_test_layout_heif_plugin_info stdout ----
thread 'bindings::bindgen_test_layout_heif_plugin_info' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `24`: Size of: heif_plugin_info', src/bindings.rs:215:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_plugin_info
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:215:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_plugin_info::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:212:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- bindings::bindgen_test_layout_heif_writer stdout ----
thread 'bindings::bindgen_test_layout_heif_writer' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `16`: Size of: heif_writer', src/bindings.rs:1458:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_writer
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:1458:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_writer::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:1455:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- bindings::bindgen_test_layout_heif_reader stdout ----
thread 'bindings::bindgen_test_layout_heif_reader' panicked at 'assertion failed: `(left == right)`
  left: `20`,
 right: `40`: Size of: heif_reader', src/bindings.rs:385:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.66.0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.66.0/library/core/src/panicking.rs:203:5
   4: libheif_sys::bindings::bindgen_test_layout_heif_reader
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:385:5
   5: libheif_sys::bindings::bindgen_test_layout_heif_reader::{{closure}}
             at /usr/share/cargo/registry/libheif-sys-1.14.2/src/bindings.rs:382:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.66.0/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    bindings::bindgen_test_layout_heif_decoding_options
    bindings::bindgen_test_layout_heif_depth_representation_info
    bindings::bindgen_test_layout_heif_encoding_options
    bindings::bindgen_test_layout_heif_error
    bindings::bindgen_test_layout_heif_plugin_info
    bindings::bindgen_test_layout_heif_reader
    bindings::bindgen_test_layout_heif_writer

test result: FAILED. 2 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s

error: test failed, to rerun pass `--lib`
dh_auto_test: error: /usr/share/cargo/bin/cargo test --all returned exit code 101

```

It looks like the mismatch is just off by the factor 2. I can patch around it for now, just letting you know that it fails on 32bit arches.

**Comment by Cykooz** [comment]
Try to enable "use-bindgen" feature for this crate. 
I think the problem in `bindings.rs` that was generated on my computer under x64 architecture.

**Comment by Cykooz** [comment]
I can't reproduce this error.
My testing environment:
- Debian Trixie x32 in Virtual Box
- Rust 1.72
- libheif-dev 1.16.2-2
- clang 14.0.6
- libheif-sys from master branch

Command to run tests:
`cargo test --features use-bindgen`

Results:
```
$ uname -a
Linux debian-x32 6.4.0-3-686-pae #1 SMP PREEMPT_DYNAMIC Debian 6.4.11-1 (2023-08-17) i686 GNU/Linux

$ cargo test --features use-bindgen
...
running 14 tests
...
test result: ok. 14 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
...
```

**Comment by werdahias** [comment]
hm, the error happend with 1.14, so maybe it's fixed now. I upload a patched 0.16 earlier; I'll test if the issue still persists. Thanks for looking into that.

**Comment by werdahias** [comment]
Still present here: just running the standalone test for libheif-sys 1.16 fails. Log: [here](https://buildd.debian.org/status/fetch.php?pkg=rust-libheif-sys&arch=i386&ver=1.16.1-1&stamp=1693393782&raw=0)

**Comment by Cykooz** [comment]
Your log is missing the "use-bindgen" string. Are you sure this feature was enabled?

**Comment by werdahias** [comment]
The debian testing just runs `cargo test` without any features.

**Comment by Cykooz** [comment]
Feature "use-bindgen" was added into default features in release 2.0.0.
